[build]
  builder = "dockerfile"

[deploy]
  # Use the container's default CMD which runs the Rails server
  # The React client is built during the Docker image build
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  restartPolicyType = "never"

[environments]
  [environments.production]
    RAILS_ENV = "production"
    RACK_ENV = "production"
    NODE_ENV = "production" 